version: '3'
services:
  app:
    build: .
    ports:
      - 5500:5500
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=someverysecurepassword
      - DB_NAME=wkldlabs
    depends_on:
      - db
  db:
    image: mysql
    ports:
      - 3316:3306
    environment:
      - MYSQL_ROOT_PASSWORD=someverysecurepassword
      - MYSQL_DATABASE=wkldlabs